# Generated by Django 2.2.3 on 2019-08-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, max_length=140, verbose_name='Address of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='Hi there I am here', max_length=140, verbose_name='Bio of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='images/default.png', upload_to='images/', verbose_name='Image of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('P', 'Parent'), ('M', 'Managerial Employee'), ('T', 'Teacher'), ('S', 'Student')], default='M', max_length=1, verbose_name='Type of User'),
            preserve_default=False,
        ),
    ]
