# Generated by Django 2.2.3 on 2019-11-07 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191105_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code of school')),
                ('name', models.CharField(max_length=100, verbose_name='Name of school')),
                ('address', models.CharField(max_length=150, verbose_name='Address of school')),
            ],
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name of grade'),
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managerialemployee',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='users.School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='schools',
            field=models.ManyToManyField(related_name='parents', to='users.School'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='users.School'),
            preserve_default=False,
        ),
    ]
